### ISSUE TITLE
Create the service worker with a helper library instead of manually

### ISSUE THREAD

**Issue by marco-c** [jkleinsc/broccoli-serviceworker#12]
You could use:
- https://github.com/mozilla/oghliner
- https://github.com/delapuente/offliner
- https://github.com/GoogleChrome/sw-precache
- https://github.com/gaia-components/serviceworkerware
- https://github.com/GoogleChrome/sw-toolbox

I or @mykmelez could help if you want to use `oghliner`.
CCing @delapuente which might help with `offliner` or `serviceworkerware`.

**Comment by jkleinsc** [comment]
@marco-c I am currently working on this using https://github.com/GoogleChrome/sw-toolbox as I think the built in [handlers](https://github.com/GoogleChrome/sw-toolbox#built-in-handlers) could be useful to developers.
