### ISSUE TITLE
precache all assets in a directory

### ISSUE THREAD

**Issue by deepan83** [jkleinsc/broccoli-serviceworker#16]
Is there a way to specify inclusion of all assets in a directory through a glob for example in the preCacheURLs definition?

**Comment by jkleinsc** [comment]
If you are using broccoli serviceworker for an Ember app, then everything in the build directory (including the assets directory) is automatically precached.  If you need to precache a different directory right now the only way to do it would be to individually list the files to precache.  The ability to specify a directory through a glob/regex would be a good feature to add.
