### ISSUE TITLE
Ember Addons Search Question

### ISSUE THREAD

**Issue by eluciano11** [jkleinsc/broccoli-serviceworker#22]
Hi @jkleinsc , thank you for this add-on. 

I'm trying to implement service workers in [emberaddons.com](https://www.emberaddons.com/) and I'm using this add-on. It works almost perfectly out of the box but I have a question/problem. On the site we display the authors gravatar and we would like to display them offline too. I managed to add the urls to the cache but I had to override the serviceworker.js `install` event and create another cache.

Example:

``` javascript
// Request the addons.js, filter the gravatar ulrs and return an array of gravatar urls.
function gravatarUrls() {
  return fetch(addonsLink).then(function(response) {
    return response.json();
  }).then(function(json) {
    return json.map(function(curr) {
      return curr['_npmUser'].gravatar + '?s=30&d=retro';
    }).filter(function(data, index, array) {
      if (array.indexOf(data) === index) {
        return data;
      }
    });
  });
}

// waitUntil expects a promise and it will stop the worker execution
// until the promise is resolved.
self.addEventListener('install', function(event) {
  event.waitUntil(
    gravatarUrls().then(function(urls) {
      // Open the specified cache if it exists. If the cache doesn't exist
      // create it and add prefetch the urls on the array.
      caches.open(GRAVATAR_CACHE).then(function(cache) {
        cache.addAll(urls);
      });

      if (self.skipWaiting) {
        self.skipWaiting();
      }
    })
  );
});
```

I wondering if their's a way to add those urls to the cache created by the toolbox? I tried using `toolbox.cache` but it didn't work. I also tried using `caches.open(CACHE_VERSION)` instead of `caches.open(GRAVATAR_CACHE)` but it didn't work.

You can see the custom service worker logic [here](https://github.com/eluciano11/ember-cli-addon-search/blob/broccoli-worker/app/serviceworkers/sw.js)

**Comment by jkleinsc** [comment]
@eluciano11 toolbox.cache should work.  You could try explicitly calling toolbox.cache(url, options) and pass in the options to it to use the same cache, eg toolbox.cache('myurl', toolbox.options).
How are you validating that toolbox.cache didn't work? The resources tab on chrome's developer tools shows you the caches used and what is in them:
![screen shot 2016-04-08 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/609052/14395301/cd2ff0e8-fd9e-11e5-825d-490383ead28c.png)

**Comment by eluciano11** [comment]
Yes, I was validating that `toolbox.cache` didn't work by looking at the Cache Storage but I hadn't notice that I had a CORS error that was being displayed on the Service Workers section.

Thank you for your help!
