### ISSUE TITLE
Force sw-toolbox version to 3.1.1

### ISSUE THREAD

**Issue by zzarcon** [jkleinsc/broccoli-serviceworker#26]
Due to this issue https://github.com/GoogleChrome/sw-toolbox/issues/143, the _sw-toolbox_ path has changed in the latest minor release (which should be major) and the package breaks when trying to require the _sw-toolbox_ library here https://github.com/jkleinsc/broccoli-serviceworker/blob/master/lib/service-worker.js#L6.

So imo the solution must be just changing `"sw-toolbox": "^3.1.1"` to `"sw-toolbox": "3.1.1"`. I'm just creating an issue instead a PR because I'm not sure if you agree with the change.

Thanks!

**Comment by jkleinsc** [comment]
@zzarcon looks like https://github.com/GoogleChrome/sw-toolbox/issues/143 has been fixed, so this issue is now fixed!
