### ISSUE TITLE
sw-toolbox.js cannot be imported when offline

### ISSUE THREAD

**Issue by knownasilya** [jkleinsc/broccoli-serviceworker#29]
Seems like the file might need to be prefetched by default? Not really sure.

> An unknown error occurred when fetching the script.
> service-worker.js:1

It errs on `importScripts('sw-toolbox.js');`. I tried adding `'/sw-toolbox.js'` to the prefetch but that doesn't fix it.

**Comment by jkleinsc** [comment]
@knownasilya I believe that any script brought in using importScripts should automatically be cached alongside the service worker.  This article here indicates that is the case:
http://www.html5rocks.com/en/tutorials/service-worker/introduction/

I'm not sure why you are encountering this error.  Do you not see the error when you are online?

**Comment by jkleinsc** [comment]
Closing due to no response.

**Comment by knownasilya** [comment]
Ops, yes I do see the error when online. 😄
