### ISSUE TITLE
Support assets on a CDN

### ISSUE THREAD

**Issue by laantorchaweb** [jkleinsc/broccoli-serviceworker#33]
Hey @jkleinsc, any ideas on how to work when the assets are on a CDN?

Right now it throws a security error, and that's expected. I tried setting `includeRegistration` to `false` so I can start the `service worker` from my domain. 

But, even if the service worker is installed none of the resources on the CDN are being cached.

**Comment by jkleinsc** [comment]
You need to specify the origin of the assets, for example

``` javascript
cacheFirstURLS: [{
  route: '/(.*)'
  options: {
    origin: 'https://yourcdn.com/'
  }
}]
```

Would use the cache first strategy on all items sitting on https://yourcdn.com/

More details about this can be found in the readme here: https://github.com/jkleinsc/broccoli-serviceworker#routing-options

**Comment by laantorchaweb** [comment]
Thanks!, this does save the assets on the cache storage with the URLs pointing correctly to the CDN. But it doesn't fetch the assets from there on the request. My vendor and app javascript files are also on the CDN, but I don't see that could be a problem.

`service-worker` and `sw-toolbox` are local files not on the CDN. I'll keep looking into it. Thanks.
