### ISSUE TITLE
Unable to build: missing sw-toolbox.js.map

### ISSUE THREAD

**Issue by bourquep** [jkleinsc/broccoli-serviceworker#42]
I am unable to build my ember app with `ember build --environment production` since integrating `broccoli-serviceworker`. I get this error:

```
Build failed.
The Broccoli Plugin: [UglifyWriter] failed with:
Error: ENOENT: no such file or directory, open '/myapp/tmp/uglify_writer-input_base_path-CQGZ0XTh.tmp/0/sw-toolbox.js.map'
```

Environment:
- ember-cli: 2.9.1
- ember: 2.6.1
- broccoli-serviceworker: 0.1.3
- node: 4.6.0

**Comment by bourquep** [comment]
I am unable to reproduce this in a brand new Ember app created with `ember new`. I'll compare build settings, environment and package versions... Tis gonna be a great morning.

**Comment by bourquep** [comment]
I am now able to reproduce with the aforementioned brand new Ember app, by enabling sourcemaps in `ember-cli-build.js`:

```
  var app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true,
      extensions: ['js']
    }
  });
```

Repro app:

[sw-test.zip](https://github.com/jkleinsc/broccoli-serviceworker/files/556180/sw-test.zip)

Simply run `ember build --environment production` on this app.

**Comment by jkleinsc** [comment]
@bourquep out of curiousity, why do you need sourcemaps in prod?

**Comment by bourquep** [comment]
We're sending uncaught errors to Airbrake, and I had enabled sourcemaps to enable meaningful backtraces in the Airbrake error reports.

Maybe there's another way, I'll investigate.

**Comment by bourquep** [comment]
For now I've disabled sourcemaps in prod builds so I can deploy my new app version with service worker.

**Comment by jkleinsc** [comment]
I see... Not sure why the problem happens, it will require some digging into.  I'm thinking the bit of code that includes the already generated sourcemap for sw-toolbox needs to take into account that build setting.

**Comment by jkleinsc** [comment]
@bourquep I found the problem.  I'll push a build tomorrow with the fix.

**Comment by jkleinsc** [comment]
@bourquep new version now available: https://www.npmjs.com/package/broccoli-serviceworker

**Comment by bourquep** [comment]
Awesome, thanks for the quick fix & deploy! I'll revert my `package.json` to the npm registry instead of my fork.

**Comment by urbany** [comment]
@jkleinsc can we add a different config option, other than debug, to define if the map should exist?
I need to have sourcemaps in staging and production but don't want to run the addon in debug mode. Maybe add a `sourcemaps`boolean? Thank you very much in advance, awesome addon :)
