### ISSUE TITLE
A page refresh does not update the app

### ISSUE THREAD

**Issue by bourquep** [jkleinsc/broccoli-serviceworker#43]
## Summary

After deploying a new version of my ember app which uses `broccoli-serviceworker`, doing a simple _Refresh_ in Chrome does not get the latest version of the app. I must do a force-refresh (shift-refresh in Chrome) to get the latest app version.

## My app/deployment configuration

* My app is deployed to Amazon S3 and served by a CloudFront distribution (HTTPS), using `ember-cli-deploy`.
* Each asset is fingerprinted, i.e. it has a hash in its filename, meaning that each deployment generates a new filename.
* I use the `ember-cli-deploy-cloudfront` addon to invalidate the CloudFront cache after each deployment, to make sure that a fresh `index.html` is used.
* I set `locationType: 'hash'` in my ember app configuration, because it is required for apps served via S3.
* I wait for the CloudFront invalidation to complete before doing a _refresh_ of my app in Chrome
* I tried excluding `index.html` from the SW cache (via `excludePaths`), but it made no difference

### environment.js

```javascript
ENV.serviceWorker = {
  enabled: true,
  debug: environment !== 'production',
  excludePaths: [
    'index.html' // I tried with and without excluding index.html, made no difference
  ],
  fastestURLs: [
    {
      route: '/(.*)',
      method: 'get',
      options: {
        origin: '//fonts.googleapis.com'
      }
    },
    {
      route: '/(.*)',
      method: 'get',
      options: {
        origin: '//fonts.gstatic.com'
      }
    }
  ],
  swIncludeFiles: [
    'bower_components/localforage/dist/localforage.js'
  ],
  swEnvironment: {
    apiOrigin: ENV.BACKEND.API_URL
  }
};
```

## Observations

~When I hit _Cmd-R_, the _Network_ pane of Chrome dev tools doesn't show a GET for `index.html`. All I see is a GET for my `service-worker-FINGERPRINT.js` file (fetched from disk cache) and other resources which are also fetched from disk cache.~

~So it looks like the browser is not fetching the updated `index.html` file at all, which means that it sticks to the previously fetched/cached `index.html`, which still uses the previous `service-worker.js` file.~

Update: my _Network_ debug view was filtered, so I wasn't seeing every request. When I hit _Cmd-R_, I do see a GET for `/`, which is fetched _from ServiceWorker_).

I'll try adding `/` to `excludePaths`...

**Comment by bourquep** [comment]
I was able to fix this by adding this to `ENV.serviceWorker`:

``` javascript
networkFirstURLs: [
  '/',
  'index.html'
],
```

And I got rid of `excludePaths`.

Shouldn't this be the default? As it is now, `/` and `index.html` are automatically configured to use the `cacheFirst` strategy, which seems to imply the browser will never again have an occasion to fetch the index page from the network, therefore never seeing newly deployed versions...

Or, if the current default makes sense and the problem I am facing is caused by something specific to my app config/deployment, maybe this should be documented in the README...

**Comment by jkleinsc** [comment]
@bourquep / and index.html are set to cacheFirst because every time the app updates the old sw cache is deleted and a new cache is created.  Using networkFirstURL's mean that those pages will always try to invoke a network request even when one isn't needed.  If that works for your app, feel free to use it, but the default for broccoli-serviceworker will be to use cacheFirst for those URLS.
