### ISSUE TITLE
After update , Serveiceworker failed to install: 

### ISSUE THREAD

**Issue by v3ss0n** [jkleinsc/broccoli-serviceworker#44]
Only way to get it working is to remove sw-toolbox.js and all references of it.
attached is the error : 

![service_worker_fail](https://cloud.githubusercontent.com/assets/419606/21266736/b1682f62-c3d5-11e6-80ba-f5a7ad7ed51c.png)

**Comment by v3ss0n** [comment]
it comes from  >>
`importScripts('sw-toolbox.js');` (1st line of `sw.js` )

**Comment by jkleinsc** [comment]
@v3ss0n I just published a new version (0.1.5).  Can you test against this version and see if it resolves your issue?

**Comment by v3ss0n** [comment]
```
(index):29 Error registering service worker:TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
(anonymous)	@	(index):29
````

**Comment by v3ss0n** [comment]
there is nothing but only console.log inside

**Comment by v3ss0n** [comment]
![screenshot_20170312_014539](https://cloud.githubusercontent.com/assets/419606/23826190/9f9dd6b4-06c5-11e7-844b-cb4c599935d1.png)

**Comment by jkleinsc** [comment]
@v3ss0n what version of Ember are you trying to do this with?  Also, what browser(s) have you tested this on?

**Comment by v3ss0n** [comment]
On chrome and ember 2.10

**Comment by jkleinsc** [comment]
@v3ss0n I found the problem.  I'll release a new version with a fix, but until then you should be able to work around the problem by adding the following to config/environment.js:

ENV.serviceWorker = {
  enabled: true
}

**Comment by jkleinsc** [comment]
Version 0.1.6 fixes this issue.  Please note you will need to run npm install and you also should clear out the bad service worker code by going to chrome://settings/cookies and removing the data for localhost
![screen shot 2017-03-16 at 3 08 42 pm](https://cloud.githubusercontent.com/assets/609052/24014225/81179d90-0a5a-11e7-9d8d-0321aeb44735.png)
